apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: node-app
    workspace: .
    docker: {}
    bazel: null
  local:
    skipPush: null
  googleCloudBuild: null
  kaniko: null
deploy:
  helm: null
  kubectl:
    manifests:
    - k8s-app.yml
  kustomize: null
